version: '3.9'
services:
  wemark-rss:
    image: ghcr.io/wemark-rss/wemark-rss:latest
    container_name: wemark-rss
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - DB=sqlite:///data/we_mp_rss.db
      - USERNAME=admin
      - PASSWORD=admin@123
    volumes:
      - ./data:/app/data

volumes:
  db_data:

networks:
  wemark-rss:


